In [3]:
import pandas as pd
df=pd.read_csv("C:/Users/samar/Desktop/samarth15/OTT platform customer churn prediction/Data/Cleaned Data/users_cleaned_final.csv")

In [4]:
df.sample(7)

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,household_size,created_at,subscription_duration_days,account_age_days,senior_user,days_since_last_login,auto_renew,payment_failures,churn,watch_hours_L30_days
3640,user_03971,beckermadeline@example.com,Kelly,Schneider,23,Female,Canada,Saskatchewan,West Sarahfurt,Premium,...,2,2024-08-25 06:19:47,1164,692,0,32,Yes,0,0,12
889,user_00975,heidihill@example.net,Richard,Harrison,37,Female,Canada,Ontario,Port Zacharyview,Premium,...,2,2025-03-09 06:59:36,847,496,0,11,Yes,1,0,51
7460,user_08101,angela86@example.org,Jamie,Lopez,54,Prefer not to say,USA,North Carolina,Barbaraland,Premium,...,2,2024-09-24 12:00:20,822,662,0,7,Yes,0,0,23
8919,user_09696,lwallace@example.net,Daniel,Moses,35,Female,USA,California,Jacobsmouth,Basic,...,5,2022-12-13 18:16:51,1310,1313,0,50,No,0,0,17
7307,user_07938,susanpham@example.net,Lori,Mccullough,39,Female,USA,Wisconsin,Lake Melindaburgh,Standard,...,2,2024-08-01 04:59:08,1127,716,0,13,No,1,0,5
4084,user_04456,anita84@example.org,Ashley,Mills,39,Male,Canada,Ontario,Tiffanyburgh,Standard,...,1,2023-07-06 05:59:41,1153,1108,0,10,No,0,0,17
4514,user_04915,mullenrebecca@example.org,Curtis,Phillips,33,Female,USA,New York,Herreraburgh,Standard,...,3,2024-12-13 04:16:09,746,582,0,55,No,0,0,6

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9476 entries, 0 to 9475
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id                     9476 non-null   object
 1   email                       9476 non-null   object
 2   first_name                  9476 non-null   object
 3   last_name                   9476 non-null   object
 4   age                         9476 non-null   int64
 5   gender                      9476 non-null   object
 6   country                     9476 non-null   object
 7   state_province              9476 non-null   object
 8   city                        9476 non-null   object
 9   subscription_plan           9476 non-null   object
 10  subscription_start_date     9476 non-null   object
 11  is_active                   9476 non-null   bool
 12  Monthly_Charge              9476 non-null   float64
 13  primary_device              9476 non-null   object
 14  household_size              9476 non-null   int64
 15  created_at                  9476 non-null   object
 16  subscription_duration_days  9476 non-null   int64
 17  account_age_days            9476 non-null   int64
 18  senior_user                 9476 non-null   int64
 19  days_since_last_login       9476 non-null   int64
 20  auto_renew                  9476 non-null   object
 21  payment_failures            9476 non-null   int64
 22  churn                       9476 non-null   int64
 23  watch_hours_L30_days        9476 non-null   int64
dtypes: bool(1), float64(1), int64(9), object(13)
memory usage: 1.7+ MB

In [14]:
# df["days_since_last_login"]
df[df["days_since_last_login"]>40]

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,household_size,created_at,subscription_duration_days,account_age_days,senior_user,days_since_last_login,auto_renew,payment_failures,churn,watch_hours_L30_days
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,...,6,2025-04-12 19:59:30,628,461,0,45,Yes,0,0,5
5,user_00006,jeffrey28@example.com,Katelyn,Hernandez,43,Female,Canada,Quebec,Carlsonfurt,Standard,...,2,2024-03-04 19:57:36,793,865,0,43,No,0,0,39
8,user_00010,morganbrianna@example.org,Adrian,Perez,24,Male,USA,Pennsylvania,Chadbury,Basic,...,1,2024-03-15 22:04:39,713,854,0,59,Yes,1,0,27
11,user_00013,richardolson@example.com,Franklin,Galloway,32,Female,USA,Ohio,Mitchellside,Basic,...,3,2023-03-29 14:38:00,1277,1207,0,56,Yes,0,0,36
14,user_00016,medinawilliam@example.org,Nicole,Wood,50,Female,USA,Pennsylvania,Bassport,Standard,...,1,2025-05-20 00:20:29,715,424,0,43,Yes,0,0,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9460,user_00248,justinross@example.net,Charles,Woods,56,Female,USA,Pennsylvania,New Joseph,Standard,...,3,2023-04-17 09:54:26,900,1188,0,44,Yes,0,0,47
9462,user_03096,pedrocruz@example.org,Jasmine,Reed,31,Male,USA,Maryland,Lake Staceyview,Basic,...,4,2023-09-18 12:34:39,881,1034,0,49,Yes,1,0,31
9464,user_05638,kevingonzalez@example.com,Brenda,Collins,38,Male,USA,Illinois,North Wesley,Standard,...,1,2022-11-06 07:41:48,1323,1350,0,56,Yes,0,0,47
9468,user_04651,tasha89@example.net,Amber,Sanchez,53,Male,Canada,Newfoundland and Labrador,North Vanessa,Premium,...,2,2022-12-31 20:22:14,486,1294,0,50,Yes,3,0,34
9469,user_01138,fallen@example.net,Michael,Garcia,56,Male,USA,North Carolina,South Sue,Premium,...,1,2024-01-01 17:49:38,723,929,0,58,Yes,0,0,28

Re-assigning churn data

In [15]:
import random

def assign_churn(days):
    if days > 45:
        return random.choices([1, 0], weights=[85, 15])[0]
    elif days > 30:
        return random.choices([1, 0], weights=[60, 40])[0]
    else:
        return random.choices([1, 0], weights=[10, 90])[0]

df["churn"] = df["days_since_last_login"].apply(assign_churn)

In [16]:
df[df["days_since_last_login"]>40]

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,household_size,created_at,subscription_duration_days,account_age_days,senior_user,days_since_last_login,auto_renew,payment_failures,churn,watch_hours_L30_days
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,...,6,2025-04-12 19:59:30,628,461,0,45,Yes,0,0,5
5,user_00006,jeffrey28@example.com,Katelyn,Hernandez,43,Female,Canada,Quebec,Carlsonfurt,Standard,...,2,2024-03-04 19:57:36,793,865,0,43,No,0,0,39
8,user_00010,morganbrianna@example.org,Adrian,Perez,24,Male,USA,Pennsylvania,Chadbury,Basic,...,1,2024-03-15 22:04:39,713,854,0,59,Yes,1,1,27
11,user_00013,richardolson@example.com,Franklin,Galloway,32,Female,USA,Ohio,Mitchellside,Basic,...,3,2023-03-29 14:38:00,1277,1207,0,56,Yes,0,1,36
14,user_00016,medinawilliam@example.org,Nicole,Wood,50,Female,USA,Pennsylvania,Bassport,Standard,...,1,2025-05-20 00:20:29,715,424,0,43,Yes,0,0,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9460,user_00248,justinross@example.net,Charles,Woods,56,Female,USA,Pennsylvania,New Joseph,Standard,...,3,2023-04-17 09:54:26,900,1188,0,44,Yes,0,1,47
9462,user_03096,pedrocruz@example.org,Jasmine,Reed,31,Male,USA,Maryland,Lake Staceyview,Basic,...,4,2023-09-18 12:34:39,881,1034,0,49,Yes,1,1,31
9464,user_05638,kevingonzalez@example.com,Brenda,Collins,38,Male,USA,Illinois,North Wesley,Standard,...,1,2022-11-06 07:41:48,1323,1350,0,56,Yes,0,1,47
9468,user_04651,tasha89@example.net,Amber,Sanchez,53,Male,Canada,Newfoundland and Labrador,North Vanessa,Premium,...,2,2022-12-31 20:22:14,486,1294,0,50,Yes,3,1,34
9469,user_01138,fallen@example.net,Michael,Garcia,56,Male,USA,North Carolina,South Sue,Premium,...,1,2024-01-01 17:49:38,723,929,0,58,Yes,0,1,28

In [19]:
df.groupby("churn").size()

churn
0    5568
1    3908
dtype: int64

In [20]:
df.to_csv("users_cleaned_final.csv")