In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/samar/Desktop/samarth15/OTT platform customer churn prediction/Data/Cleaned Data/users_cleaned.csv")

In [4]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,Monthly_Charge,primary_device,household_size,created_at,churn
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,9.99,Laptop,1,2023-04-01 14:40:50,0
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,29.99,Desktop,2,2024-10-10 15:39:11,0
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,15.99,Desktop,3,2024-06-29 14:27:49,1
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,15.99,Laptop,2,2023-04-11 01:01:59,0
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,15.99,Desktop,6,2025-04-12 19:59:30,0

adding subcsription duration days column

In [7]:
today=pd.Timestamp.today()
df["subscription_start_date"]=pd.to_datetime(df["subscription_start_date"])
df["subscription_duration_days"]=(today-df["subscription_start_date"]).dt.days

In [17]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,Monthly_Charge,primary_device,household_size,created_at,subscription_duration_days,account_age_days
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,9.99,Laptop,1,2023-04-01 14:40:50,831,1204
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,29.99,Desktop,2,2024-10-10 15:39:11,785,646
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,15.99,Desktop,3,2024-06-29 14:27:49,1030,749
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,15.99,Laptop,2,2023-04-11 01:01:59,696,1194
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,15.99,Desktop,6,2025-04-12 19:59:30,628,461

In [9]:
df=df.drop("churn",axis=1)

Adding account_age_days Column

In [18]:
df["created_at"].dtype
#df.info()
df["created_at"]=pd.to_datetime(df["created_at"])
df["account_age_days"]=(today-df["created_at"]).dt.days

adding senior_user column

In [19]:
df["senior_user"] = (
    df["age"] >= 60
).astype(int)

In [20]:
import numpy as np

Adding watch_hours column

In [21]:
df["Watch_hours"]=np.random.randint(0,101,size=len(df))

Adding days_since_last_login column

In [23]:
df["days_since_last_login"]=np.random.randint(0,61,size=len(df))

adding Auto renew column

In [27]:
df["auto_renew"]=np.random.choice(["Yes","No"],size=len(df),p=[0.75,0.25])

adding payment failures column

In [29]:
df["paymenr_failures"]=np.random.choice([0,1,2,3],size=len(df),p=[0.75,0.15,0.07,0.03])

In [30]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,primary_device,household_size,created_at,subscription_duration_days,account_age_days,senior_user,Watch_hours,days_since_last_login,auto_renew,paymenr_failures
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,...,Laptop,1,2023-04-01 14:40:50,831,1204,0,0,15,Yes,0
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,...,Desktop,2,2024-10-10 15:39:11,785,646,0,14,28,Yes,1
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,...,Desktop,3,2024-06-29 14:27:49,1030,749,0,43,12,Yes,0
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,...,Laptop,2,2023-04-11 01:01:59,696,1194,0,99,28,Yes,2
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,...,Desktop,6,2025-04-12 19:59:30,628,461,0,24,45,Yes,0

In [46]:
df.rename(columns={"Watch_hours":"watch_hours_L30_days"},inplace=True)
df.rename(columns={"paymenr_failures":"payment_failures"},inplace=True)

In [47]:

conditions = (
    (df["watch_hours_L30_days"] < 15) &
    (df["days_since_last_login"] > 15) &
    (df["payment_failures"] >= 1) &
    (df["auto_renew"] == "No")
)

df["churn"] = np.where(conditions, 1, 0)

In [52]:
df.tail()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,household_size,created_at,subscription_duration_days,account_age_days,senior_user,days_since_last_login,auto_renew,payment_failures,churn,watch_hours_L30_days
9471,user_04613,glawson@example.com,Diane,Thomas,8,Female,USA,Georgia,Wandamouth,Premium,...,3,2025-01-03 18:42:59,699,561,0,4,Yes,0,0,50
9472,user_09468,mcox@example.org,Laurie,Young,37,Female,USA,North Carolina,Gomezshire,Basic,...,2,2023-04-22 01:11:07,1390,1183,0,9,Yes,0,0,35
9473,user_09414,mcdonaldkeith@example.net,James,Dillon,39,Male,USA,Tennessee,North Dennischester,Standard,...,2,2022-08-11 09:56:11,976,1437,0,33,Yes,0,0,22
9474,user_07950,adam74@example.net,Isaac,Cook,35,Female,Canada,Alberta,Ellenchester,Basic,...,5,2024-12-09 21:10:19,374,585,0,40,Yes,0,0,19
9475,user_09958,debraking@example.com,Amber,Phillips,35,Male,USA,Pennsylvania,Rogerberg,Premium+,...,5,2024-07-21 03:27:05,621,727,0,17,Yes,0,0,56

In [49]:
df["Watch_hours"]=np.random.randint(0,61,size=len(df))

In [54]:
df.to_csv("users_cleaned_final.csv",index=False)

In [56]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,...,household_size,created_at,subscription_duration_days,account_age_days,senior_user,days_since_last_login,auto_renew,payment_failures,churn,watch_hours_L30_days
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,...,1,2023-04-01 14:40:50,831,1204,0,15,Yes,0,0,33
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,...,2,2024-10-10 15:39:11,785,646,0,28,Yes,1,0,37
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,...,3,2024-06-29 14:27:49,1030,749,0,12,Yes,0,0,40
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,...,2,2023-04-11 01:01:59,696,1194,0,28,Yes,2,0,26
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,...,6,2025-04-12 19:59:30,628,461,0,45,Yes,0,0,5

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9476 entries, 0 to 9475
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id                     9476 non-null   object
 1   email                       9476 non-null   object
 2   first_name                  9476 non-null   object
 3   last_name                   9476 non-null   object
 4   age                         9476 non-null   int64
 5   gender                      9476 non-null   object
 6   country                     9476 non-null   object
 7   state_province              9476 non-null   object
 8   city                        9476 non-null   object
 9   subscription_plan           9476 non-null   object
 10  subscription_start_date     9476 non-null   datetime64[ns]
 11  is_active                   9476 non-null   bool
 12  Monthly_Charge              9476 non-null   float64
 13  primary_device              9476 non-null   object
 14  household_size              9476 non-null   int64
 15  created_at                  9476 non-null   datetime64[ns]
 16  subscription_duration_days  9476 non-null   int64
 17  account_age_days            9476 non-null   int64
 18  senior_user                 9476 non-null   int64
 19  days_since_last_login       9476 non-null   int32
 20  auto_renew                  9476 non-null   object
 21  payment_failures            9476 non-null   int64
 22  churn                       9476 non-null   int64
 23  watch_hours_L30_days        9476 non-null   int32
dtypes: bool(1), datetime64[ns](2), float64(1), int32(2), int64(7), object(11)
memory usage: 1.6+ MB

In [57]:
df["is_active"]

0        True
1        True
2       False
3        True
4        True
        ...
9471     True
9472    False
9473     True
9474     True
9475     True
Name: is_active, Length: 9476, dtype: bool