In [2]:
import pandas as pd

In [5]:
df= pd.read_csv("C:/Users/samar/Desktop/samarth15/OTT platform customer churn prediction/Data/users.csv")

In [9]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,monthly_spend,primary_device,household_size,created_at
0,user_00001,figueroajohn@example.org,Erica,Garza,43.0,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,36.06,Laptop,1.0,2023-04-01 14:40:50.540242
1,user_00002,blakeerik@example.com,Joshua,Bernard,38.0,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,14.59,Desktop,2.0,2024-10-10 15:39:11.030515
2,user_00003,smiller@example.net,Barbara,Williams,32.0,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,11.71,Desktop,3.0,2024-06-29 14:27:49.560875
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11.0,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,28.56,Laptop,2.0,2023-04-11 01:01:59.614841
4,user_00005,richard13@example.net,Jason,Foster,21.0,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,9.54,Desktop,6.0,2025-04-12 19:59:30.137806

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  10300 non-null  object
 1   email                    10300 non-null  object
 2   first_name               10300 non-null  object
 3   last_name                10300 non-null  object
 4   age                      9071 non-null   float64
 5   gender                   9476 non-null   object
 6   country                  10300 non-null  object
 7   state_province           10300 non-null  object
 8   city                     10300 non-null  object
 9   subscription_plan        10300 non-null  object
 10  subscription_start_date  10300 non-null  object
 11  is_active                10300 non-null  bool
 12  monthly_spend            9283 non-null   float64
 13  primary_device           10300 non-null  object
 14  household_size           8755 non-null   float64
 15  created_at               10300 non-null  object
dtypes: bool(1), float64(3), object(12)
memory usage: 1.2+ MB

df.describe()

Handling Missing Values

In [14]:
df["age"].isnull().sum()

np.int64(1229)

In [20]:
med=df["age"].median()
#print(med)
df["age"]=df["age"].fillna(med)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  10300 non-null  object
 1   email                    10300 non-null  object
 2   first_name               10300 non-null  object
 3   last_name                10300 non-null  object
 4   age                      10300 non-null  float64
 5   gender                   9476 non-null   object
 6   country                  10300 non-null  object
 7   state_province           10300 non-null  object
 8   city                     10300 non-null  object
 9   subscription_plan        10300 non-null  object
 10  subscription_start_date  10300 non-null  object
 11  is_active                10300 non-null  bool
 12  monthly_spend            9283 non-null   float64
 13  primary_device           10300 non-null  object
 14  household_size           8755 non-null   float64
 15  created_at               10300 non-null  object
dtypes: bool(1), float64(3), object(12)
memory usage: 1.2+ MB

In [23]:
df["age"]=df["age"].astype(in)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  10300 non-null  object
 1   email                    10300 non-null  object
 2   first_name               10300 non-null  object
 3   last_name                10300 non-null  object
 4   age                      10300 non-null  int64
 5   gender                   9476 non-null   object
 6   country                  10300 non-null  object
 7   state_province           10300 non-null  object
 8   city                     10300 non-null  object
 9   subscription_plan        10300 non-null  object
 10  subscription_start_date  10300 non-null  object
 11  is_active                10300 non-null  bool
 12  monthly_spend            9283 non-null   float64
 13  primary_device           10300 non-null  object
 14  household_size           8755 non-null   float64
 15  created_at               10300 non-null  object
dtypes: bool(1), float64(2), int64(1), object(12)
memory usage: 1.2+ MB

In [30]:
df.loc[25:35,"age"]

25    60
26    37
27    35
28    28
29    24
30    26
31    56
32    60
33    32
34    31
35    36
Name: age, dtype: int64

Removing Rows with null gender

In [31]:
df=df.dropna(subset=["gender"])

In [36]:
df.info()
#df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  9476 non-null   object
 1   email                    9476 non-null   object
 2   first_name               9476 non-null   object
 3   last_name                9476 non-null   object
 4   age                      9476 non-null   int64
 5   gender                   9476 non-null   object
 6   country                  9476 non-null   object
 7   state_province           9476 non-null   object
 8   city                     9476 non-null   object
 9   subscription_plan        9476 non-null   object
 10  subscription_start_date  9476 non-null   object
 11  is_active                9476 non-null   bool
 12  monthly_spend            8551 non-null   float64
 13  primary_device           9476 non-null   object
 14  household_size           8040 non-null   float64
 15  created_at               9476 non-null   object
dtypes: bool(1), float64(2), int64(1), object(12)
memory usage: 1.2+ MB

In [37]:
df.head(15)

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,monthly_spend,primary_device,household_size,created_at
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,36.06,Laptop,1.0,2023-04-01 14:40:50.540242
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,14.59,Desktop,2.0,2024-10-10 15:39:11.030515
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,11.71,Desktop,3.0,2024-06-29 14:27:49.560875
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,28.56,Laptop,2.0,2023-04-11 01:01:59.614841
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,9.54,Desktop,6.0,2025-04-12 19:59:30.137806
5,user_00006,jeffrey28@example.com,Katelyn,Hernandez,43,Female,Canada,Quebec,Carlsonfurt,Standard,2024-05-16,True,NaN,Gaming Console,2.0,2024-03-04 19:57:36.106319
7,user_00008,nathanielmartin@example.net,Carol,Smith,35,Male,Canada,New Brunswick,Johnbury,Basic,2022-11-03,True,6.69,Tablet,1.0,2025-01-13 04:53:02.134116
8,user_00009,donnaarroyo@example.org,Allison,Brandt,24,Male,USA,North Carolina,Raymondstad,Premium,2025-04-13,True,12.21,Gaming Console,5.0,2022-12-13 15:46:23.391721
9,user_00010,morganbrianna@example.org,Adrian,Perez,24,Male,USA,Pennsylvania,Chadbury,Basic,2024-08-04,True,23.18,Laptop,1.0,2024-03-15 22:04:39.445799
10,user_00011,kristenaguirre@example.org,Collin,Gomez,67,Female,USA,Ohio,Shieldston,Basic,2022-10-07,True,556.13,Desktop,2.0,2024-12-27 07:05:50.526519
11,user_00012,jamesherrera@example.org,Isaiah,Wright,41,Female,USA,Missouri,Mortonside,Premium,2022-09-26,True,29.23,Tablet,2.0,2025-06-29 19:39:28.228369
12,user_00013,richardolson@example.com,Franklin,Galloway,32,Female,USA,Ohio,Mitchellside,Basic,2023-01-18,True,18.68,Gaming Console,3.0,2023-03-29 14:38:00.334657
13,user_00014,adkinsbrian@example.net,Wesley,Brown,22,Male,USA,Pennsylvania,North Brooke,Basic,2023-10-18,True,25.19,Laptop,2.0,2024-04-28 09:41:18.589372
14,user_00015,barnesbrandy@example.net,Sarah,Santiago,45,Female,Canada,Alberta,West Randy,Basic,2023-12-16,False,5.14,Mobile,3.0,2022-08-13 06:39:47.240847
15,user_00016,medinawilliam@example.org,Nicole,Wood,50,Female,USA,Pennsylvania,Bassport,Standard,2024-08-02,True,3.36,Laptop,1.0,2025-05-20 00:20:29.058670

In [42]:
df=df.rename(columns={"monthly_spend":"Monthly_Charge"})

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  9476 non-null   object
 1   email                    9476 non-null   object
 2   first_name               9476 non-null   object
 3   last_name                9476 non-null   object
 4   age                      9476 non-null   int64
 5   gender                   9476 non-null   object
 6   country                  9476 non-null   object
 7   state_province           9476 non-null   object
 8   city                     9476 non-null   object
 9   subscription_plan        9476 non-null   object
 10  subscription_start_date  9476 non-null   object
 11  is_active                9476 non-null   bool
 12  Monthly_Charge           8734 non-null   float64
 13  primary_device           9476 non-null   object
 14  household_size           8040 non-null   float64
 15  created_at               9476 non-null   object
dtypes: bool(1), float64(2), int64(1), object(12)
memory usage: 1.2+ MB

In [45]:
df.loc[df["subscription_plan"]=="Basic","Monthly_Charge"]=9.99

In [46]:
df.loc[df["subscription_plan"]=="Basic","Monthly_Charge"]

0        9.99
7        9.99
9        9.99
10       9.99
12       9.99
         ...
10289    9.99
10290    9.99
10294    9.99
10296    9.99
10298    9.99
Name: Monthly_Charge, Length: 1858, dtype: float64

In [48]:
df.loc[df["subscription_plan"]=="Standard","Monthly_Charge"]=15.99

In [49]:
df.loc[df["subscription_plan"]=="Premium","Monthly_Charge"]=21.99

In [50]:
df.loc[df["subscription_plan"]=="Premium+","Monthly_Charge"]=29.99

In [60]:
df=df.rename(columns={"monthly_spend":"Monthly_Charge_$)"})

In [61]:
df.head()

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,Monthly_Charge,primary_device,household_size,created_at
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,9.99,Laptop,1.0,2023-04-01 14:40:50.540242
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,29.99,Desktop,2.0,2024-10-10 15:39:11.030515
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,15.99,Desktop,3.0,2024-06-29 14:27:49.560875
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,15.99,Laptop,2.0,2023-04-11 01:01:59.614841
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,15.99,Desktop,6.0,2025-04-12 19:59:30.137806

In [63]:
df["Monthly_Charge"].isnull().sum()

np.int64(0)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  9476 non-null   object
 1   email                    9476 non-null   object
 2   first_name               9476 non-null   object
 3   last_name                9476 non-null   object
 4   age                      9476 non-null   int64
 5   gender                   9476 non-null   object
 6   country                  9476 non-null   object
 7   state_province           9476 non-null   object
 8   city                     9476 non-null   object
 9   subscription_plan        9476 non-null   object
 10  subscription_start_date  9476 non-null   object
 11  is_active                9476 non-null   bool
 12  Monthly_Charge           9476 non-null   float64
 13  primary_device           9476 non-null   object
 14  household_size           8040 non-null   float64
 15  created_at               9476 non-null   object
dtypes: bool(1), float64(2), int64(1), object(12)
memory usage: 1.2+ MB

In [66]:
median_h=df["household_size"].median()
mean_h=df["household_size"].mean()
print(median_h)
print(mean_h)

2.0
2.865174129353234

In [67]:
df["household_size"]=df["household_size"].fillna(median_h)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10299
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  9476 non-null   object
 1   email                    9476 non-null   object
 2   first_name               9476 non-null   object
 3   last_name                9476 non-null   object
 4   age                      9476 non-null   int64
 5   gender                   9476 non-null   object
 6   country                  9476 non-null   object
 7   state_province           9476 non-null   object
 8   city                     9476 non-null   object
 9   subscription_plan        9476 non-null   object
 10  subscription_start_date  9476 non-null   datetime64[ns]
 11  is_active                9476 non-null   bool
 12  Monthly_Charge           9476 non-null   float64
 13  primary_device           9476 non-null   object
 14  household_size           9476 non-null   int64
 15  created_at               9476 non-null   datetime64[ns]
dtypes: bool(1), datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 1.2+ MB

In [69]:
df["subscription_start_date"]=pd.to_datetime(df["subscription_start_date"])

In [71]:
df["created_at"] = pd.to_datetime(df["created_at"])

In [81]:
df.head(12)

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,Monthly_Charge,primary_device,household_size,created_at,churn
0,user_00001,figueroajohn@example.org,Erica,Garza,43,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,9.99,Laptop,1,2023-04-01 14:40:50,0
1,user_00002,blakeerik@example.com,Joshua,Bernard,38,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,29.99,Desktop,2,2024-10-10 15:39:11,0
2,user_00003,smiller@example.net,Barbara,Williams,32,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,15.99,Desktop,3,2024-06-29 14:27:49,1
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,15.99,Laptop,2,2023-04-11 01:01:59,0
4,user_00005,richard13@example.net,Jason,Foster,21,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,15.99,Desktop,6,2025-04-12 19:59:30,0
5,user_00006,jeffrey28@example.com,Katelyn,Hernandez,43,Female,Canada,Quebec,Carlsonfurt,Standard,2024-05-16,True,15.99,Gaming Console,2,2024-03-04 19:57:36,0
7,user_00008,nathanielmartin@example.net,Carol,Smith,35,Male,Canada,New Brunswick,Johnbury,Basic,2022-11-03,True,9.99,Tablet,1,2025-01-13 04:53:02,0
8,user_00009,donnaarroyo@example.org,Allison,Brandt,24,Male,USA,North Carolina,Raymondstad,Premium,2025-04-13,True,21.99,Gaming Console,5,2022-12-13 15:46:23,0
9,user_00010,morganbrianna@example.org,Adrian,Perez,24,Male,USA,Pennsylvania,Chadbury,Basic,2024-08-04,True,9.99,Laptop,1,2024-03-15 22:04:39,0
10,user_00011,kristenaguirre@example.org,Collin,Gomez,67,Female,USA,Ohio,Shieldston,Basic,2022-10-07,True,9.99,Desktop,2,2024-12-27 07:05:50,0
11,user_00012,jamesherrera@example.org,Isaiah,Wright,41,Female,USA,Missouri,Mortonside,Premium,2022-09-26,True,21.99,Tablet,2,2025-06-29 19:39:28,0
12,user_00013,richardolson@example.com,Franklin,Galloway,32,Female,USA,Ohio,Mitchellside,Basic,2023-01-18,True,9.99,Gaming Console,3,2023-03-29 14:38:00,0

In [74]:
df["created_at"]=df["created_at"].dt.floor("s")

In [77]:
df["household_size"] = df["household_size"].astype(int)

Adding New Column "churn"

In [79]:
df["churn"] = df["is_active"].map({
    True: 0,
    False: 1
})

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9476 entries, 0 to 10299
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  9476 non-null   object
 1   email                    9476 non-null   object
 2   first_name               9476 non-null   object
 3   last_name                9476 non-null   object
 4   age                      9476 non-null   int64
 5   gender                   9476 non-null   object
 6   country                  9476 non-null   object
 7   state_province           9476 non-null   object
 8   city                     9476 non-null   object
 9   subscription_plan        9476 non-null   object
 10  subscription_start_date  9476 non-null   datetime64[ns]
 11  is_active                9476 non-null   bool
 12  Monthly_Charge           9476 non-null   float64
 13  primary_device           9476 non-null   object
 14  household_size           9476 non-null   int64
 15  created_at               9476 non-null   datetime64[ns]
 16  churn                    9476 non-null   int64
dtypes: bool(1), datetime64[ns](2), float64(1), int64(3), object(10)
memory usage: 1.2+ MB

In [82]:
df.loc[df["is_active"]==False,["is_active","churn"]]

       is_active  churn
2          False      1
14         False      1
24         False      1
49         False      1
50         False      1
...          ...    ...
10266      False      1
10271      False      1
10284      False      1
10291      False      1
10296      False      1

[1393 rows x 2 columns]

Saving Cleaned Data

In [84]:
df.to_csv("C:/Users/samar/Desktop/samarth15/OTT platform customer churn prediction/Data/Cleaned Data/users_cleaned.csv",index=False)